plugins {
    id("groovy")
    //id("com.gradleup.shadow") version "9.0.0"
    id("io.micronaut.library") version "4.6.2"
    id("codenarc")
    id("java-library")
    id("java-test-fixtures")
    id "com.vanniktech.maven.publish" version "0.34.0"
}


dependencies {
    implementation("jakarta.annotation:jakarta.annotation-api")
    implementation("io.micronaut:micronaut-management")
    compileOnly("io.micronaut:micronaut-inject-groovy")

    runtimeOnly("org.postgresql:postgresql")
    runtimeOnly("org.flywaydb:flyway-database-postgresql")

    implementation("io.micronaut.flyway:micronaut-flyway")
    implementation("org.flywaydb:flyway-core")
    compileOnly("io.micronaut.data:micronaut-data-processor")
    compileOnly("io.micronaut.validation:micronaut-validation-processor")
    implementation("io.micronaut.data:micronaut-data-jdbc")
    implementation("io.micronaut.cache:micronaut-cache-core")
//    implementation("io.micronaut.cache:micronaut-cache-ehcache")
    implementation("io.micronaut.cache:micronaut-cache-caffeine")
    implementation("io.micronaut.cache:micronaut-cache-management")

    testRuntimeOnly("org.testcontainers:testcontainers:2.0.3")
    testRuntimeOnly("org.testcontainers:postgresql:1.21.4")
    testRuntimeOnly("org.postgresql:postgresql")

    testFixturesImplementation("io.micronaut.test:micronaut-test-spock")
    testFixturesImplementation("io.micronaut.sql:micronaut-jdbc-hikari")
    testFixturesImplementation("org.junit.jupiter:junit-jupiter-api:5.14.4")
    testFixturesImplementation("org.junit.jupiter:junit-jupiter-engine:5.14.4")

    // To find flyway migrations in jars
    implementation 'io.github.classgraph:classgraph:4.8.191'

    implementation project(':mauro-domain')
}

jar {
    exclude("**/logback.xml")
}
