package org.maurodata.domain.comparison

import groovy.transform.CompileStatic

@CompileStatic
enum ComparisonConclusion {
    STRUCTURALLY_IDENTICAL,
    LEFT_STRUCTURALLY_NARROWS_RIGHT,
    RIGHT_STRUCTURALLY_NARROWS_LEFT,
    STRUCTURALLY_OVERLAPPING,
    STRUCTURALLY_DISJOINT,
    STRUCTURALLY_INCOMPATIBLE,
    STRUCTURALLY_DIFFERENT,
    LEFT_IS_SUBSET_OF_RIGHT,
    RIGHT_IS_SUBSET_OF_LEFT,
    SETS_EQUAL,
    SETS_OVERLAP,
    SETS_DISJOINT,
    NOT_COMPARABLE_BY_THIS_PROVIDER
}
