plugins {
    id("groovy")
    //id("com.gradleup.shadow") version "9.0.0"
    id("io.micronaut.library") version "4.6.2"
    id("codenarc")
    id "com.vanniktech.maven.publish" version "0.34.0"
}


dependencies {
    implementation("io.micronaut.data:micronaut-data-processor")

    // camel case
    implementation("com.google.guava:guava:33.7.1-jre")

    // For parsing java dates / instants
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")

    // For importer parameters introspection
    implementation('org.apache.commons:commons-lang3:3.20.0')
}


