micronaut:
  server:
    port: -1
  http:
    services:
      mauro:
        url: 'http://localhost:2345'
#       apikey: 1234
    client:
      read-timeout: 10m      # Read timeout
      connect-timeout: 100s
  security:
    enabled: false
mauro:
  login:
    retry-wait: 0
  search:
    rebuild:
      poll-inactivity-period: 2s
      poll-interval: 1s